server:
  port: 10230
  host: 0.0.0.0
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"
#  experimental:
#    http2:
#      enable: true
#      max-content-length: 16384

pipe:
  target:
    scheme: http
    host: exploration-lds
    port: 9091
    namespace: ns
    source: metadata

tracing:
  enabled: false
  service: test-application
  sampler-type: const
  sampler-param: 1
  propagation: b3
  protocol: http
  host: localhost
  port: 14268
  path: /api/traces
  paths:
    - path: "/favicon.ico"
      enabled: false
    - path: "/metrics"
      enabled: false
    - path: "/metrics/vendor"
      enabled: false
    - path: "/metrics/base"
      enabled: false
    - path: "/metrics/application"
      enabled: false
    - path: "/health"
      enabled: false
    - path: "/health/live"
      enabled: false
    - path: "/health/ready"
      enabled: false

pubsub:
  enabled: true
  admin: true
  use-emulator: true
  emulator:
    host: localhost
    port: 8538
  credential-provider: emulator
  credentials:
    service-account:
      path: secret/my-service-account-key.json
    compute-engine:
    emulator:
    default:
  upstream:
    projectId: dapla
    topic: exploration-metadata-1
    subscription: exploration-metadata-dev
